### ISSUE TITLE
Request: add icopy.site to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#106]
Evidence: https://qa.icopy.site/questions/62596990/avro-schema-evolution-with-enum-deserialization-crashes
Original: https://stackoverflow.com/questions/62596990/avro-schema-evolution-with-enum-deserialization-crashes

Generally it seems that copycat behavior is not limited to just https://qa.icopy.site , but multiple subdomains under http://icopy.site/

**Comment by quenhus** [comment]
Thanks a lot!
