### ISSUE TITLE
Request: add 520liyan.xyz to the filter

### ISSUE THREAD

**Issue by xcasxcursex** [quenhus/uBlock-Origin-dev-filter#110]
Evidence: https://520liyan.xyz/fzwoch/obs-teleport
Original: https://github.com/fzwoch/obs-teleport

Thanks

**Comment by quenhus** [comment]
This domain seems to be down since your submission. Is it up for you?

**Comment by xcasxcursex** [comment]
I'm getting a 502 error. It's making for misleading search results, though: 
![image](https://user-images.githubusercontent.com/58130821/169709819-4b86870f-c670-47e2-a366-76e9357112a8.png)

**Comment by quenhus** [comment]
As the website is still down, I won't add it. Search engines will soon remove it from results. I'm adding a tag on this issue, to be able to find this domain if it is back online.

**Comment by xcasxcursex** [comment]
Good call. Thanks!
