### ISSUE TITLE
Request: add javaallin.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#111]
Evidence: https://www.javaallin.com/code/write-avro-files-with-logicaltype-timestamp-millis-on-date-timestamps-in-java.html
Original: https://stackoverflow.com/questions/62696580/write-avro-files-with-logicaltype-timestamp-millis-on-date-timestamps-in-java

**Comment by quenhus** [comment]
This domain seems to be down since your submission. Is it up for you?

**Comment by quenhus** [comment]
Sorry for my late response. I'm adding a tag on this issue, to be able to find this domain if it is back online.
