### ISSUE TITLE
Request: add multiple sites to the filter

### ISSUE THREAD

**Issue by soredake** [quenhus/uBlock-Origin-dev-filter#114]
Evidence:
https://frameboxxindore.com/android/you-asked-where-can-i-find-logcat-in-android.html
https://qa.wujigu.com/qa/?qa=780691/where-are-android-logcat-files-stored
https://shenzhenjia.net/qa/?qa=780691/
https://ogeek.cn/qa/?qa=780691/&show=780692
https://devdreamz.com/question/533322-where-are-android-logcat-files-stored

Original: https://stackoverflow.com/questions/4424544/where-are-android-logcat-files-stored

**Comment by quenhus** [comment]
Thanks a lot!
