### ISSUE TITLE
Request: add ebestcode.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#119]
Evidence: https://ebestcode.com/fr/comment-puis-je-dfinir-un-logicaltype-dans-un-schma-spark-avro-24.html
Original: https://stackoverflow.com/questions/54560068/how-can-i-set-a-logicaltype-in-a-spark-avro-2-4-schema

**Comment by quenhus** [comment]
Thanks a lot!
