### ISSUE TITLE
Request: add peaku.co to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#122]
Evidence: https://peaku.co/questions/27569-el-esquema-avro-con-logicaltype-no-se-puede-usar-con-el-ultimo-confluent-kafka
Original: https://stackoverflow.com/questions/70302559/avro-schema-with-logicaltype-cant-be-used-with-latest-confluent-kafka

**Comment by quenhus** [comment]
Thanks a lot!
