### ISSUE TITLE
Request: add solveforum.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#125]
Evidence: https://solveforum.com/forums/threads/solved-how-to-send-a-byte-array-in-kafka-with-avro-schema-registry.834807/
Original: https://stackoverflow.com/questions/71895490/how-to-send-a-byte-array-in-kafka-with-avro-schema-registry

**Comment by quenhus** [comment]
Thanks a lot!
