### ISSUE TITLE
Request: add askdevz.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#128]
Evidence: https://askdevz.com/question/761977-why-are-there-two-options-to-read-a-csv-file-in-pyspark-which-one-should-i-use
Original: https://stackoverflow.com/questions/58261793/why-are-there-two-options-to-read-a-csv-file-in-pyspark-which-one-should-i-use

**Comment by quenhus** [comment]
Thanks a lot!
