### ISSUE TITLE
Request: add devasking.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#129]
Evidence: https://www.devasking.com/issue/avro-field-default-values
Original: https://stackoverflow.com/questions/22938124/avro-field-default-values
and https://github.com/FasterXML/jackson-dataformats-binary/issues/207

This is a bit of an odd one. It seems to mix and match results from different sites....

**Comment by quenhus** [comment]
Thanks a lot!
