### ISSUE TITLE
Add metadata to filter lists

### ISSUE THREAD

**Issue by quinncomendant** [quenhus/uBlock-Origin-dev-filter#13]
Filter lists using the Adblock syntax can have metadata in [special comments](https://help.eyeo.com/adblockplus/how-to-write-filters#special-comments) in the header. This helps identify the name of the list, its origin, refresh frequency, etc. For example:

```
! Title: uBlock-Origin-dev-filter
! Version: 12345
! Expires: 1 day
! Description: Filters to block and remove copycat-websites from DuckDuckGo and Google. Specific to dev websites like StackOverflow or GitHub.
! Homepage: https://github.com/quenhus/uBlock-Origin-dev-filter
```

One side-effect of not having this, is the lack of title after importing the uBlock-Origin-dev-filter list:
![Screen Shot 2022-01-22 at 11 27 52](https://user-images.githubusercontent.com/6884276/150649162-4789097f-e328-4b4b-8e44-f811695b08cf.png)

Thanks!

**Comment by quenhus** [comment]
Thanks a lot, I looked into doing this at the beginning, but I couldn't find the way

**Comment by quinncomendant** [comment]
After removing and re-adding the filter list, its name is now correctly displayed in uBlock Origin:

![Screen Shot 2022-01-22 at 14 12 57](https://user-images.githubusercontent.com/6884276/150654051-4f97ef53-8103-4982-8f53-0c235d583f7b.png)

Thanks for the quick fix!
