### ISSUE TITLE
Request: add cans.pro to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#135]
Evidence: https://cans.pro/topic/databricks-avro-schema-%E0%B9%84%E0%B8%A1%E0%B9%88%E0%B8%AA%E0%B8%B2%E0%B8%A1%E0%B8%B2%E0%B8%A3%E0%B8%96%E0%B9%81%E0%B8%9B%E0%B8%A5%E0%B8%87%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99-spark-sql-structtype/45074144
Original: https://stackoverflow.com/questions/45074144/databricks-avro-schema-cannot-be-converted-to-a-spark-sql-structtype

**Comment by quenhus** [comment]
Thanks a lot!
