### ISSUE TITLE
1 filter containing everything

### ISSUE THREAD

**Issue by notDavid** [quenhus/uBlock-Origin-dev-filter#138]
Hi there,

please consider making 1 filter which contains everything:
- All search engines currently available in the repo and all that might be added in the future
- All copycat-websites currently available in the repo and all that might be added in the future

Thank you :-)

**Comment by quenhus** [comment]
Hi, I don't really understand the use-case, but I will add it when I find time.

"All copycat-websites currently available in the repo and all that might be added in the future" flavors already exists and is named `all`.

How can I name the "All seach engines" flavor? : `All SE` or `Every SE`?

**Comment by quenhus** [comment]
To recap:
- `dev` (formerly called `all`): Dev-oriented copycat-websites
- `global`: All copycat-websites currently available in the repo and all that might be added in the future

For search engines:
- `All Search Engines`: All search engines currently available in the repo and all that might be added in the future

More info in the [README](https://github.com/quenhus/uBlock-Origin-dev-filter).
