### ISSUE TITLE
Request: add jonic.cn to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#139]
Evidence: https://jonic.cn/qa/?qa=929514/scala-is-there-a-way-to-add-extra-metadata-for-spark-dataframes
Original: https://stackoverflow.com/questions/32628845/is-there-a-way-to-add-extra-metadata-for-spark-dataframes

Current entry for jonic.cn does not filter above example. 
```
*://*.jonic.cn/*
```
Many thanks!

**Comment by quenhus** [comment]
Will be corrected by #143
