### ISSUE TITLE
Request: add studytonight.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#141]
Evidence: https://www.studytonight.com/forum/how-to-list-the-tables-in-a-sqlite-database-file-that-was-opened-with-attach
Original: https://stackoverflow.com/questions/82875/how-can-i-list-the-tables-in-a-sqlite-database-file-that-was-opened-with-attach

**Comment by quenhus** [comment]
Thanks a lot!
