### ISSUE TITLE
Correct subdomain wildcard filter

### ISSUE THREAD

**Issue by quenhus** [quenhus/uBlock-Origin-dev-filter#143]
In uBO `*.domain.example` does not filter `domain.example` and all of its subdomain, as I always though. We need to correct the current filter to achieve the desired behavior. I have to clarify how uBO blocks domains and subdomain. 

It is important to note that we have different forms of filters in the current blocklist:
- `*://domain.example/*`: domain
- `*://*.domain.example/*`: domain and subdomains
- `*://domain.example/abc/*`: domain and path. We might convert this form to a domain only filter (`*://domain.example/*`).

**Comment by quenhus** [comment]
[This](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#host-files) seems to be the solution. We might use filters with the syntax `||example.com^`.

I need to test it, but I didn't find time for now'

**Comment by quenhus** [comment]
Seems to work:
`*://domain.example/*` ➡ `||domain.example^`
`*://www.domain.example/*` ➡ `||www.domain.example^`
`*://*.domain.example/*` ➡ `||domain.example^`
`*://domain.example/abc/*` ➡ `||domain.example/abc$all`

**Comment by quenhus** [comment]
https://github.com/quenhus/uBlock-Origin-dev-filter/pull/149#issuecomment-1162206125

> One may use filters in the branch `test--feat-correct-ubo-wildcard` to test if the new filter syntax is correct. Will merge next week if nobody finds an issue.
> 
> Example of filter you may test: [Filter](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/test--feat-correct-ubo-wildcard/dist/google/global.txt)

**Comment by WarmWelcome** [comment]
This doesn't seem to be correct anymore. I am having an issue where it is not targeting any subdomains with the normal url and it tells me bad domain when I try anything involving * or ||.
