### ISSUE TITLE
Request: add faqcodes.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#145]
Evidence: https://www.faqcodes.com/faq/625211/how-to-convert-a-struct-field-in-a-row-to-an-avro-record-in-spark-java
Original: https://stackoverflow.com/questions/63925187/how-to-convert-a-struct-field-in-a-row-to-an-avro-record-in-spark-java

**Comment by quenhus** [comment]
Thanks a lot!
