### ISSUE TITLE
Request: add thecodeteacher.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#150]
Evidence: https://www.thecodeteacher.com/question/26087/spring---Can-not-deserialize-instance-of-java.util.ArrayList-out-of-START_OBJECT-token
Original: https://stackoverflow.com/questions/20837856/can-not-deserialize-instance-of-java-util-arraylist-out-of-start-object-token

**Comment by quenhus** [comment]
Thanks a lot!
