### ISSUE TITLE
Request: add devtip.in to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#151]
Evidence: https://devtip.in/25510083/cannot-deserialize-instance-of-object-out-of-start_array-token-in-spring-webservice%7D
Original: https://stackoverflow.com/questions/25510083/cannot-deserialize-instance-of-object-out-of-start-array-token-in-spring-webserv

**Comment by quenhus** [comment]
Thanks a lot!
