### ISSUE TITLE
Request: add cardiologie-tonkin.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#172]
Evidence: https://stackoverflow.com/questions/295579/fastest-way-to-determine-if-an-integers-square-root-is-an-integer
Original: http://cardiologie-tonkin.com/questions/295579/fastest-way-to-determine-if-an-integers-square-root-is-an-integer

**Comment by quenhus** [comment]
As the website seems to be down, I won't add it. I'm adding a tag on this issue, to be able to find this domain if it is back online.
