### ISSUE TITLE
Request: add ittone.ma to the filter

### ISSUE THREAD

**Issue by daigennki** [quenhus/uBlock-Origin-dev-filter#175]
Evidence: https://ittone.ma/ittone/konsole-always-open-new-window-instead-of-tab/
Original: https://askubuntu.com/questions/1408583/konsole-always-open-new-window-instead-of-tab

Found in DDG search results. Obvious copycat with cryptocurrency ads. :unamused:

**Comment by quenhus** [comment]
As the website seems to be down, I won't add it. I'm adding a tag on this issue, to be able to find this domain if it is back online.
