### ISSUE TITLE
Request: add adoclib.com/blog to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#180]
Evidence: https://www.adoclib.com/blog/failed-with-exception-java-io-ioexception-org-apache-avro-avrotypeexception-found-long-expecting-union-in-hive.html
Original: https://stackoverflow.com/questions/35480155/failed-with-exception-java-io-ioexceptionorg-apache-avro-avrotypeexception-fou

Attempt to trick search engines by copying stackoverflow questions.

**Comment by quenhus** [comment]
Thanks a lot!
