### ISSUE TITLE
Request: add socket.dev/npm to the filter

### ISSUE THREAD

**Issue by gervasiocaj** [quenhus/uBlock-Origin-dev-filter#181]
Evidence: https://socket.dev/npm/package/@cloudflare/pages-plugin-static-forms 
Original: https://www.npmjs.com/package/@cloudflare/pages-plugin-static-forms

**Comment by quenhus** [comment]
I'm not sure this website is a simple mirror, as it provides information about packages. The goal of the website seems to be security of the supply chain, which is one of the main challenge for open-source packages.

I'm not sure I will add it to the filter.
