### ISSUE TITLE
Request: add libraries.io/npm to the filter

### ISSUE THREAD

**Issue by gervasiocaj** [quenhus/uBlock-Origin-dev-filter#182]
Evidence: https://libraries.io/npm/@cloudflare%2Fpages-plugin-static-forms
Original: https://www.npmjs.com/package/@cloudflare/pages-plugin-static-forms

**Comment by quenhus** [comment]
I'm not sure this website is a simple mirror. The goal of the website is to aggregate information from several package managers, which can be helpful for some users. No malicious content here (ads, cryptominer) and it has clear attribution.

I'm not sure I will add it to the filter.
