### ISSUE TITLE
Request: add invalidtype.com to the filter

### ISSUE THREAD

**Issue by sersorrel** [quenhus/uBlock-Origin-dev-filter#184]
Evidence: https://invalidtype.com/what-is-fix-in-haskell-and-why-does-fix-error-print-an-infinite-string-and-why-also-take-10-fix-error-does-the-same-too/  
Original: https://stackoverflow.com/questions/72133599/what-is-fix-in-haskell-and-why-does-fix-error-print-an-infinite-string-and

**Comment by quenhus** [comment]
Thanks a lot!

Closed by 9f957831863b6811b1c427737e0e2fd9ed1124ea
