### ISSUE TITLE
Request: add winmundo.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#187]
Evidence: https://winmundo.com/biztalk-tools-for-converting-x12-to-xml-based-on-an-xsd-schema/
Original: https://stackoverflow.com/questions/58282694/tools-for-converting-x12-to-xml-based-on-an-xsd-schema

**Comment by quenhus** [comment]
Thanks a lot!

Closed by 9f957831863b6811b1c427737e0e2fd9ed1124ea
