### ISSUE TITLE
Request: add issuehint.com to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#189]
Evidence: https://issuehint.com/issue/bijij/ViewImage/229
Original: https://github.com/bijij/ViewImage/issues/229

Evidence: https://issuehint.com/issue/quenhus/uBlock-Origin-dev-filter/115
Original: https://github.com/quenhus/uBlock-Origin-dev-filter/issues/115

**Comment by quenhus** [comment]
Thanks a lot!
