### ISSUE TITLE
Request: add spiegato.com to the filter

### ISSUE THREAD

**Issue by trashman9000** [quenhus/uBlock-Origin-dev-filter#191]
Evidence: https://spiegato.com
Original: ???

Results are unlikely to be written by a person due to the sheer volume, text regularity (suggestive of a template or pattern at work) and plenitude of languages offered. Searching for text fragments doesn't yield anything which suggests that the original source might have been passed through a paraphrasing program similar to QuillBot.

**Comment by quenhus** [comment]
Thanks a lot!

Closed by d3a3690ef34e12b4dae11f2b0eee679c105f4920
