### ISSUE TITLE
Add Brave Search support

### ISSUE THREAD

**Issue by adworacz** [quenhus/uBlock-Origin-dev-filter#2]
Just posting this here as a feature request. I might eventually get the time to add this myself, but I figured it's good to post this here in case other users are looking for the support.

Effectively, we'd just need to expand the Google + DuckDuckGo support to include `search.brave.com` as well.

**Comment by quenhus** [comment]
Thanks. Resolved by 290eb75

**Comment by adworacz** [comment]
Thank you for addressing it so fast!
