### ISSUE TITLE
Request: add dapper-tutorial.net to the filter

### ISSUE THREAD

**Issue by vborovikov** [quenhus/uBlock-Origin-dev-filter#20]
DDG query: dapper insert multiple rows
FAKE: https://dapper-tutorial.net/knowledge-base/49864946/does-dapper-support-inserting-multiple-rows-in-a-single-query-
REAL: https://stackoverflow.com/questions/49864946/does-dapper-support-inserting-multiple-rows-in-a-single-query

Thanks!

**Comment by quenhus** [comment]
Thanks!
