### ISSUE TITLE
Request: add tistory.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#201]
Evidence: https://rateye.tistory.com/780
Original: https://stackoverflow.com/questions/4462478/jslint-is-suddenly-reporting-use-the-function-form-of-use-strict

Evidence: https://codestyle.tistory.com/691
Original: https://stackoverflow.com/questions/4462478/jslint-is-suddenly-reporting-use-the-function-form-of-use-strict

**Comment by yous** [comment]
tistory.com is a Korean blog service. Every `*.tistory.com` domain is given to a user, so you should block `rateye.tistory.com` and `codestyle.tistory.com`, not the whole domain.

**Comment by quenhus** [comment]
Thanks a lot! Corrected
