### ISSUE TITLE
Add cmsdk.com

### ISSUE THREAD

**Issue by joeframbach** [quenhus/uBlock-Origin-dev-filter#21]
cmsdk.com cropped up recently, another copycat.

**Comment by quenhus** [comment]
Thanks!

Please provide evidence to ease my work.
Original: https://stackoverflow.com/questions/60121647/select-from-multiple-tables-in-sequelize
Copycat: https://cmsdk.com/node-js/select-from-multiple-tables-in-sequelize.html
