### ISSUE TITLE
Request: add lightrun.com/answers to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#217]
Evidence: https://lightrun.com/answers/microsoft-wsl-wsl-2-nic-bridge-mode--has-tcp-workaround
Original: https://github.com/microsoft/WSL/issues/4150

https://lightrun.com/answers is a collection of github issues.

**Comment by quenhus** [comment]
Thanks a lot!

**Comment by HarukaMa** [comment]
You might want to limit the filter to `*://lightrun.com/answers/*` as it seems Lightrun is also a legit business.

Disclaimer: not affiliated, just noticed some seemingly normal search results are being removed.

**Comment by quenhus** [comment]
Thanks a lot for your contribution. Sorry I totally miss the notification. You are right.
