### ISSUE TITLE
Request: add dailydevsblog.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#218]
Evidence: https://dailydevsblog.com/troubleshoot/resolved-in-avro-schema-how-to-wrap-the-array-to-an-object-and-put-it-as-a-union-instead-of-putting-just-array-as-union-102643/
Original: https://stackoverflow.com/questions/71216862/in-avro-schema-how-to-wrap-the-array-to-an-object-and-put-it-as-a-union-instead

**Comment by quenhus** [comment]
Thanks a lot!
