### ISSUE TITLE
Static filter syntax for duckduckgo

### ISSUE THREAD

**Issue by dgcampea** [quenhus/uBlock-Origin-dev-filter#22]
If I'm interpreting ublock's [Procedural filters](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) right, static filters should be used instead (if possible).
For _duckduckgo_:
```
duckduckgo.com##[data-domain$="gitmemory.com"]
```
instead of
https://github.com/quenhus/uBlock-Origin-dev-filter/blob/9c5e535cb435bb8b5ec930f9a1f798e906aee945/dist/duckduckgo/github_copycats.txt#L14

**Comment by quenhus** [comment]
I don't understand which part of the documentation your are referring to.
However, you're right, your example would optimize the filter, and I will use it from now on.

**Comment by quenhus** [comment]
Resolved by ab4b095f8d0342f1f4876add78db2b621b64ed30
