### ISSUE TITLE
Request: add developerfacts.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#221]
Evidence: https://developerfacts.com/answer/59895-how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
Original: https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script

**Comment by quenhus** [comment]
Thanks a lot!
