### ISSUE TITLE
Request: add copyprogramming.com to the filter

### ISSUE THREAD

**Issue by Arnavion** [quenhus/uBlock-Origin-dev-filter#222]
Evidence: https://copyprogramming.com/howto/when-to-use-routable-vs-non-routable-ip-addresses
Original: https://serverfault.com/questions/725666/when-to-use-routable-vs-non-routable-ip-addresses

The opening blurb is also taken from one of the answers, in fact the page itself duplicates it in "Solution 2".

**Comment by quenhus** [comment]
Thanks a lot!
