### ISSUE TITLE
Request: add devpick.io to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#228]
Evidence: https://devpick.io/project?name=jefferyto/Google-Cache-Continue-Redux
Original: https://github.com/jefferyto/Google-Cache-Continue-Redux

Evidence: https://devpick.io/developer?name=jefferyto
Original: https://github.com/jefferyto

Note that external URLs have appended a reference parameter (see jefferyto's profile on the right):
https://thingsthemselves.com/?ref=https://devpick.io

In a bit of maybe SEO, all/most of the /project pages have the same tagline attached to the top: "I think it's a good project so I recommend it to you.":

Evidence: https://devpick.io/project?name=simonlindholm/toggle-gifs
Original: https://github.com/simonlindholm/toggle-gifs

**Comment by quenhus** [comment]
Thanks a lot!
