### ISSUE TITLE
Request: add grabthiscode.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#232]
Evidence: https://grabthiscode.com/sql/org-apache-spark-sql-avro-incompatibleschemaexception-unexpected-type-org-apache-spark-ml-linalg-vectorudt
Original: https://stackoverflow.com/questions/42838430/incompatibleschemaexception-unexpected-type-vectorudt-when-serializing-in-avro

**Comment by quenhus** [comment]
Thanks a lot!

Already closed by 6e42da1ebed4c533ad2aa0903e6dd58fef98df86
