### ISSUE TITLE
Request: add technointeract.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#240]
Evidence: https://www.technointeract.com/?qa=779/how-to-parse-string-format-yyyy-localdate-using-java-time-api
Original: https://stackoverflow.com/questions/23800477/java-8-time-api-how-to-parse-string-of-format-mm-yyyy-to-localdate

This one is trying to 'hide' by rephrasing some words, although it clearly is a stackoverflow copcat.

**Comment by quenhus** [comment]
Thanks a lot!
