### ISSUE TITLE
Request: add saca.aussievitamin.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#241]
Evidence: http://saca.aussievitamin.com/qa-https-stackoverflow.com/questions/3437059/does-python-have-a-string-contains-substring-method
Original: https://stackoverflow.com/questions/3437059/does-python-have-a-string-contains-substring-method

Is this a new thing? I have seen this type of redirection before.....

**Comment by quenhus** [comment]
Thanks a lot!

I'm not seeing anything actually. I'm getting a rate-limiting error from StackOverflow. The website must be a simple proxy to SO. I added it to the filter.
