### ISSUE TITLE
Request: add wikifix.dev to the filter

### ISSUE THREAD

**Issue by fabstu** [quenhus/uBlock-Origin-dev-filter#249]
Evidence: https://wikifix.dev/swift-compiler-error-type-watermark-does-not-conform-to-protocol-viewmodifier-id957916
Original: https://stackoverflow.com/questions/64576987/swift-compiler-error-type-watermark-does-not-conform-to-protocol-viewmodifi

**Comment by quenhus** [comment]
Thanks a lot!
