### ISSUE TITLE
OK to include in the letsblock.it project?

### ISSUE THREAD

**Issue by xvello** [quenhus/uBlock-Origin-dev-filter#25]
Hello @quenhus,

I am the maintainer of https://letsblock.it, a uBlock Origin list generator that allows users to pick and customize filter templates to filter out low-value content. The most requested feature so far is to extend the [hide websites from search results](https://letsblock.it/filters/search-results) template with presets to hide Github and Stackoverflow copycats. Instead of duplicating work, I'd love to reuse the data from your project and import it as user-selectable presets.

I am currently working on the implementation PR: https://github.com/xvello/letsblockit/pull/64 and will deploy a staging version when the frontend is ready. I'd love to have your input on it, whether that's questions, ideas or concerns.

**Comment by quenhus** [comment]
Hello,
Thanks for your work for a better Web experience. Use [_my_](https://github.com/quenhus/uBlock-Origin-dev-filter/graphs/contributors) work as much as you need.

To ensure the list is kept up to date, I suggest you append a link to this project along with the checkbox to activate presets. Maybe a tiny GitHub icon, or something more visible. This way, users will be able to contribute and suggest new copycats. 

However, as the license indicates, you don't have to give credit to this project, if you don't want to.

I didn't have time to look at it, but maybe we could work together to improve performance of our filters, and add support for other search-engines.

Nice work! 🎉🇫🇷

**Comment by xvello** [comment]
Merci!

Of course I am linking back to the source! Here's a screenshot of the work in progress:

![image](https://user-images.githubusercontent.com/6241083/153620074-8a989421-af3e-44fe-914d-c7cf46526d15.png)

Feel free to take [the Kagi.com support](https://github.com/xvello/letsblockit/commit/8851eb392cea22bc582761e87d8b87f2a3346d63), Searx would be harder with your model, as there are plenty of instances on different domains.

**Comment by quenhus** [comment]
Great work!

Will take a look for Kagi.

**Comment by xvello** [comment]
It's online on https://staging.letsblock.it/filters/search-results if you want to give it a try!
I'll review and merge it tomorrow.

**Comment by xvello** [comment]
Merged and deployed, thanks for agreeing to this!
I'll watch the repo and sync the values, but don't hesitate to give me a heads up if breaking changes were to occur.
