### ISSUE TITLE
Request: add 12 URLs to the filter

### ISSUE THREAD

**Issue by S-trace** [quenhus/uBlock-Origin-dev-filter#26]
ask-ubuntu.ru - askubuntu.com translation, has origin link
Evidence: https://ask-ubuntu.ru/questions/2337/ispravit-povrezhdennyij-razdel-ntfs-bez-windows
Original: https://askubuntu.com/questions/47700/fix-corrupt-ntfs-partition-without-windows

askubuntu.ru - askubuntu.com translation, no origin link
Evidence: https://askubuntu.ru/questions/170334/vosstanovit-ntfs-bez-windows-dublikat
Original: https://askubuntu.com/questions/330733/repair-ntfs-without-windows

kompsekret.ru - superuser.com translation, origin link leads to its own page
Evidence: https://kompsekret.ru/q/best-ways-to-fix-outlook-2007-error-your-mailbox-is-over-its-size-limit-288222/
Original: https://superuser.com/questions/293412/best-ways-to-fix-outlook-2007-error-your-mailbox-is-over-its-size-limit

ohandroid.com - stackoverflow.com translation, no origin link, answers merged with the question in one chunk
Evidence: http://www.ohandroid.com/android-widget-switch-toggled-event-listener.html
Original: https://stackoverflow.com/questions/21010924/android-widget-switch-toggled-event-listener/21010941

poweruser.guru - superuser.com translation, has origin link
Evidence: https://poweruser.guru/questions/324399/проводник-windows-держит-дескриптор-открытым-на-исполняемых-файлах
Original: https://superuser.com/questions/324399/windows-explorer-keeps-handle-open-on-executable-files

ruphp.com - stackoverflow.com translation, no origin link, answers merged with the question in one chunk
Evidence: https://ruphp.com/google-x43e-2.html
Original: https://stackoverflow.com/questions/10549049/accessing-google-bookmarks-server-side-with-php

server-fault.ru - serverfault.com translation, origin link leads to its own page
Evidence: https://server-fault.ru/questions/273014/kak-vosstanovit-zapisat-metku-klonirovat-suschestvujuschuju
Original: https://serverfault.com/questions/1085397/how-can-one-recover-write-a-label-clone-existing-one

sprosi.pro - stackoverflow.com translation, has origin link
Evidence: https://sprosi.pro/questions/824506/kak-mne-obnovit-razvetvlennyiy-repozitoriy-github
Original: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

stackru.com - stackoverflow.com translation, has origin link
Evidence: https://stackru.com/questions/2261423/eclipse-javalangclassnotfoundexception
Original: https://stackoverflow.com/questions/1052978/eclipse-java-lang-classnotfoundexception

switch-case.ru - redirect to answer-id.com/ru/

ubuntugeeks.com - askubuntu.com translation, has origin link
Evidence: https://ubuntugeeks.com/questions/1/how-to-check-internet-speed-via-terminal
Original: https://askubuntu.com/questions/104755/how-to-check-internet-speed-via-terminal

ubuntuplace.info - askubuntu.com translation, has origin link
Evidence: https://ubuntuplace.info/questions/1/comment-verifier-la-vitesse-internet-le-terminal
Original: https://askubuntu.com/questions/104755/how-to-check-internet-speed-via-terminal

wikiroot.ru - superuser.com translation, no origin link
Evidence: https://wikiroot.ru/question/moy-bios-zavisaet-na-testirovanie-pamyati-chto-mojet-vyzvaty-eto
Original: https://superuser.com/questions/185086/my-bios-hangs-at-testing-memory-what-could-cause-this

russianblogs.com - no direct evidence, but looks very copycat site

Some dead links which can resurrect somedays:
fliplinux.com
issue.life
javahow.ru
programmerz.ru
qaru.site
ru.craftjs.com
stackoverrun.com
unix.stackovernet.com
vpros.ru

**Comment by quenhus** [comment]
Thanks a lot for this documented and detailed contribution!

It didn't add the last website (russianblogs[.]com), as it is not strictly a [copycat to me](https://github.com/quenhus/uBlock-Origin-dev-filter/issues/19#issuecomment-1031681698). However, I am entirely open to any comments on that.

I didn't add dead links, but will do as soon as they are back online.

Thank you again!
