### ISSUE TITLE
Request: add www.opensourceagenda.com to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#267]
Evidence: https://www.opensourceagenda.com/projects/uso-archive
Original: https://github.com/33kk/uso-archive

Evidence: https://www.opensourceagenda.com/resources/50-top-php-interview-questions-and-answers
Original: https://www.techgeekbuzz.com/blog/php-interview-questions/

Evidence: https://www.opensourceagenda.com/projects/github-wc-polyfill/versions
Original: https://github.com/JustOff/github-wc-polyfill/releases

Not much effort put into the pages... At least the original source is linked right on the pages! 😃 
I don't know if that makes the site actually _more_ useful... 👀

**Comment by quenhus** [comment]
Thanks a lot!
