### ISSUE TITLE
Request: filtering stackoverflow 'forwarders'

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#269]
I have encountered several of these 'forwarding' stackoverflow copycats now. Hopefully this is not a new trend....
The only thing they have in common is '-https-stackoverflow.com' in the url. Is there a way to filter based on that?

Many thanks!

Evidence: http://lac.youramys.com/cara-https-stackoverflow.com/questions/522563/accessing-the-index-in-for-loops
Original: https://stackoverflow.com/questions/522563/accessing-the-index-in-for-loops

Evidence: http://zequ.aussievitamin.com/qa-https-stackoverflow.com/posts/54867/revisions
Original: https://stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python

Evidence: http://kili.railpage.com.au/cara-https-stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python
Original: https://stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python

**Comment by quenhus** [comment]
Thanks a lot!

I don't really know how to filter these. What is the point of the redirection?

We could filter `*://*-https-stackoverflow.com*` but it could have a lot of side effects.

Some more:
Evidence: https://www.januari.live/tugas-https-stackoverflow.com/questions/tagged/libreoffice+excel+excel-formula

Evidence: https://www.stackexchange.live/tugas-https-stackoverflow.com/questions/tagged/libreoffice+excel+excel-formula

Evidence: https://www.kamis.live/terjawab-https-stackoverflow.com/questions/8202204/how-to-validate-jquery-ui-combobox-values-with-jquery-validation-plugin

**Comment by quenhus** [comment]
saca.aussievitamin.com, mars.railpage.com.au and aing.railpage.com.au are already in the list. 
I don't understand because otherwise this domain seems to be legit (or maybe a SEO spam).
