### ISSUE TITLE
Request: add Wikipedia clones

### ISSUE THREAD

**Issue by oxguy3** [quenhus/uBlock-Origin-dev-filter#28]
Another category of copycat sites that I find maddening are Wikipedia clones. Wikipedia is freely licensed and even [allows database dumps](https://en.wikipedia.org/wiki/Wikipedia:Database_download), so there are a _ton_ of annoying mirrors out there. These sites can show up in search results for just about any topic. Here are a few:

```
*://www.wikiwand.com/*
*://wiki2.org/*
*://worddisk.com/wiki/*
*://thereaderwiki.com/*
*://www.absoluteastronomy.com/*
*://encyclopedia.thefreedictionary.com/*
*://peoplepill.com/*
*://www.algebra.com/algebra/about/history/*.wikipedia
```
You can see that these are clones from the following links:
* https://www.wikiwand.com/
* https://wiki2.org/
* https://worddisk.com/wiki/search/
* https://thereaderwiki.com/en/
* http://www.absoluteastronomy.com/ (just click any link and scroll to the bottom to see the attribution)
* https://encyclopedia.thefreedictionary.com/
* https://peoplepill.com/ (just click any link and scroll to the bottom to see the attribution)
* https://www.algebra.com/algebra/about/history/Main_Page.wikipedia

There are a lot more copycats out there (Wikipedia maintains [a giant list](https://en.wikipedia.org/wiki/Wikipedia:Mirrors_and_forks), but it includes many sites that have just copied a small amount of content and not the entire site, and I'm sure there are some dead/outdated entries as well), but I figured I'd just post a few to start.

**Comment by quenhus** [comment]
More of them (highly ranked in search engine):
- wikizero.com
- dbpedia.org
- wikiless.org
- everything.explained.today
- www.wiwa.wiki
- findatwiki.com
- www.wikide.wiki
- www.scholarship.edu.vn
- www.secret-bases.co.uk
- www.wikit.wiki

**Comment by xvello** [comment]
> I need users' opinion:
> Should the all filter include Wikipedia copycats, or should Wikipedia filter remain separated?

Scope creep is inevitable in both enterprise and open-source projects ;) It boils down to what you are happy and comfortable maintaining.

I think you should distribute several presets:

- `all` would be everything in the repository
- `dev` would be the opinionated selection for the original audience of the project

|  | dev | all |
|---|---|---|
| Github copycats | X | X |
| Stackoverflow copycats | X | X |
| NPM mirrors |  | X |
| Wikipedia copycats |  | X |

**Comment by quenhus** [comment]
@xvello Just to be sure, why NPM mirrors would not be in the `dev` filter?

I'm not sure I want to create a new preset. When the scope of the present slightly change (as seen with `all.txt`), users might feel fooled. And, I just cannot notify them of the change of scope.

To me, the best way is to subscribe to every filters you want, individually (for example DDG-SO + Brave-SO + DDG-GH)

**Comment by xvello** [comment]
You had reservations about adding NPM to the default preset, that's why I left if out of the `dev` preset example.

I agree that silently adding new categories in a preset is a double-edged sword, that's why in letsblock.it I don't enable new options for existing users, even if the default value for new users is `true`. I show an `updated` bubble to ask the user to explicitly enable/disable it.

Getting away from presets altogether, and asking users to explicitly chose what list to use can be a good option indeed. You can make it easier with subscribe links like I described in https://github.com/quenhus/uBlock-Origin-dev-filter/pull/32#issuecomment-1044184956

**Comment by quenhus** [comment]
@xvello Btw, thanks a lot for your high-quality contributions and implication with this project. It is highly appreciated. (same for @nelsonjchen for sure)

I'm going to completely rewrite the README, and heavily use [#32 (comment)](https://github.com/quenhus/uBlock-Origin-dev-filter/pull/32#issuecomment-1044184956) with a clear table of all filters. Fun fact: I was talking of this feature with the creator of uBlock Origin [yesterday on HN](https://news.ycombinator.com/item?id=30380135).

Something as:

|     | Google                                                                                                                                                                                                                                                                                                                                         | DuckDuckGo                                                                                                                                                                                                                                                                                                                                     | Startpage                                                                                                                                                                                                                                                                                                                                      | Brave                                                                                                                                                                                                                                                                                                                                          | Google+DDG                                                                                                                                                                                                                                                                                                                                     | Ecosia                                                                                                                                                                                                                                                                                                                                         |
|-----|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| dev | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=de3f32&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=fdd20a&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=5b7bca&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=f25100&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=9b59b6&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=36acb8&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) |
| all | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=de3f32&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=fdd20a&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=5b7bca&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=f25100&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=9b59b6&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) | [![uBO - add this filter](https://img.shields.io/static/v1?label=uBO&message=add+this+filter&color=36acb8&style=flatlogo=uBlock+Origin)](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fquenhus%2FuBlock-Origin-dev-filter%2Fmain%2Fdist%2Fgoogle_duckduckgo%2Fall.txt&title=Google%2BDuckDuckGo%20All) |

On another table with all flavors (GitHub-only, SO-only, Wikipedia-only, ...)

**Comment by quenhus** [comment]
I'm going to try to accept/add only websites [which](https://github.com/quenhus/uBlock-Origin-dev-filter/issues/19#issuecomment-1031681698):
> offers no benefits for users over the original resource.

I do consider that _projects created for privacy concerns_ offer benefits to users. However, these websites should not use aggressive SEO techniques to catch users who would have otherwise reached the original resource.
