### ISSUE TITLE
GitHub Raw isn't meant for serving files

### ISSUE THREAD

**Issue by ryleu** [quenhus/uBlock-Origin-dev-filter#29]
GitHub Raw isn't made for serving files to tons of people, even though it *can*, so I would recommend setting up Pages on this repo to reduce strain on GitHub's systems.

**Comment by quenhus** [comment]
Do you have any resource that explains that GitHub Raw should not be used as a CDN?

Even uBlock Origin uses GitHub Raw as CDN for default filters.

Here is the list of network requests when updating uBO filters:
<img src="https://i.imgur.com/6YCGiGv_d.webp?maxwidth=760&fidelity=grand" width="600px">

uBO has 10 millions users, and it seams that GitHub has no problem with GitHub Raw being used as a CDN.

**Comment by ryleu** [comment]
https://stackoverflow.com/a/5503156

It can be slower. The URLs are also smaller if you use Pages. 

Beyond that, there are no real benefits unless you're serving web files, which you aren't.

From what I remember, though I don't have time to find where I read this, Pages caches more aggressively, which leads to the decreased latency.

**Comment by nelsonjchen** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/5363/154614613-ed252921-4aed-4a05-80f2-a4ff3d601ccf.png">

FWIW, GitHub Raw appears to be behind a CDN (fast.ly) itself anyway. If there's load, it's probably not much on GitHub and it's how uBO is ok/GitHub is OK with it.

**Comment by quenhus** [comment]
GitHub Raw and GitHub pages share the same config (4 IPs for CDN/loadbalancer perf, same HTTP cache headers, Etag, both use varnish...)

I highly suspect GitHub is using the same tools/storage/cache/config for both Raw and pages.

Close for now, feel free to re-open if you have more information on that.
