### ISSUE TITLE
Request: add multiple sites to the filter

### ISSUE THREAD

**Issue by amartos** [quenhus/uBlock-Origin-dev-filter#290]
Hi.

Here are two sites translating stack (respectively in french and spanish):

* progaide.com
* iteramos.com

Note that "progaide" was marked "domain down" in #227 but as of today, the site is up on my side.

Evidence: https://prograide.com/pregunta/49633/confusion-sur-le-systeme-personnalise-emacs
Evidence: https://www.iteramos.com/pregunta/56255/confuso-acerca-de-emacs-sistema-personalizado
Original: https://stackoverflow.com/questions/12058717/confusing-about-the-emacs-custom-system

**Comment by quenhus** [comment]
Thanks a lot!
