### ISSUE TITLE
Request: add itw01.com to the filter

### ISSUE THREAD

**Issue by KAIYOHUGO** [quenhus/uBlock-Origin-dev-filter#292]
Evidence: https://itw01.com/QCF3LE2.html
Original: https://www.tecmint.com/zulip-team-group-chat-app-for-linux/

**Comment by quenhus** [comment]
Thanks a lot!

Evidence: https://itw01.com/8JHR8EG.html
Original: https://medium.com/preezma/memory-leaks-in-javascript-and-how-to-avoid-them-63916a02f68
