### ISSUE TITLE
Request: add codertw.com to the filter

### ISSUE THREAD

**Issue by KAIYOHUGO** [quenhus/uBlock-Origin-dev-filter#293]
Evidence: https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/119024/  
Original: https://zhuanlan.zhihu.com/p/29134624  (maybe?)

If you scroll down to the bottom of the copycat page, you can see the original website insert some text to try to prevent copycat.

![](https://user-images.githubusercontent.com/41114603/190657652-f60f5ce2-797a-459d-ad9a-c852d506661a.png)

It say "anti copycat website, origin : http://bigsec.com/", but the website is down.

**Comment by quenhus** [comment]
Thanks a lot!

Evidence: codertw.com
Original: https://www.oracle.com/webfolder/technetwork/tutorials/obe/em/emgc1110/installemgc11101linux/emgc11101install.htm
