### ISSUE TITLE
Explain how this is different from Anti-AutoTranslation list

### ISSUE THREAD

**Issue by patrakov** [quenhus/uBlock-Origin-dev-filter#30]
https://github.com/Nebula-Mechanica/Anti-AutoTranslation-List/ is another project with exactly the same goal.

**Comment by matteoturini** [comment]
*all* clones, not just auto translated

**Comment by quenhus** [comment]
I didn't know this project existed, so I created my own, for my own needs. It shares the same goal, so I can't "Explain how this is different from Anti-AutoTranslation".

However here are differences:
- it is not my own filter, matching my needs;
- it does not include mirrors, but auto-translations (according to README);
- it has not been updated for 7 month;
- it concat filters for every search engine, which is not great for performance;
- it uses 5 filters for DDG, 4 for Google, which is not great for performance (although my filters are certainly not perfect either);
- it has less users, which inevitably implies less contributors/data updates.
