### ISSUE TITLE
Request: add wikiless.org to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#301]
Evidence: https://wikiless.org/wiki/Wedding_of_Princess_Beatrix_of_the_Netherlands_and_Claus_van_Amsberg?lang=en
Original: https://en.wikipedia.org/wiki/Wedding_of_Princess_Beatrix_of_the_Netherlands_and_Claus_van_Amsberg

**Comment by quenhus** [comment]
Thanks a lot!

I won't add wikiless.org, as there are privacy considerations with this website. 

See : https://github.com/quenhus/uBlock-Origin-dev-filter/issues/28#issuecomment-1044705792

From the README of the filter:
> I do not consider a mirror created for privacy concern to be a copycat, except if it uses aggressive SEO techniques;
