### ISSUE TITLE
When you though copy websites are the only struggle

### ISSUE THREAD

**Issue by Feirell** [quenhus/uBlock-Origin-dev-filter#306]
When you really though copycat websites were the peak of bullshit.

Came across this channel by searching for a question:
https://www.youtube.com/channel/UCaZL4eLD7a30Fa8QI-sRi_g

Those are auto generated videos from StackOverflow Questions, when you though it could not get any worse.

**Comment by quenhus** [comment]
Thanks a lot for this! 

It is terrible and so annoying. However, I can't block these videos. Closing with "won't fix".

**Comment by Feirell** [comment]
Yeah sure, was just something ridiculous I found :)
