### ISSUE TITLE
Request: add many to the filter

### ISSUE THREAD

**Issue by matteoturini** [quenhus/uBlock-Origin-dev-filter#31]
Please block many mirrors

![2022-02-17_21-23](https://user-images.githubusercontent.com/69425093/154593956-bb09f70c-27a3-400a-8667-d311c24cb4d0.png)

Evidences:
https://gitfreak.com/skyra-project
https://cnpmjs.org/package/@aero/klasa/v/0.5.0-rc1
https://npmmirror.com/package/@aero/klasa
Original:
[github](https://github.com/skyra-project)
[npmjs](https://www.npmjs.com/package/@aero/klasa)

**Comment by quenhus** [comment]
The first one (gitfreak[.]com) is indeed a GitHub copycat. 

However the others are actually npm mirrors, which are not currently handle by my project. It seams that npmjs[.com] is blocked in China, so these mirrors allows to have access to npm from China. I'm not sure what to do with them.

**Comment by quenhus** [comment]
Partially resolved by 57a72f6105bea397d051def2c423776d474c8d13 for gitfreak[.]com.

**Comment by DarkestEmpire** [comment]
https://pythonawesome.com please add this also

**Comment by matteoturini** [comment]
Open a new issue

Em sex., 18 de fev. de 2022 07:54, Agent Shadow ***@***.***>
escreveu:

**Comment by quenhus** [comment]
Thanks!
Closed by 6bb7e97b6036ba7e74864b10f5cfe5959254e255
