### ISSUE TITLE
Request: add narkive.fr (and .com, etc... ?) to the filter

### ISSUE THREAD

**Issue by amartos** [quenhus/uBlock-Origin-dev-filter#317]
I'm a little hesitant on this one. On one side, it is obviously translating SE pages and thus is an annoyance as it pollutes the web searches results -- this is, of course, my own opinion. On the other, it is supposed to be a newsgroup archive, and it mentions the translation (bottom of the page).

I made a quick visit to the .com TLD and it's the same group, in case you want to add more domains from it (note: it really likes captchas...). `narkive.jp` is already in the filter, though, so I thought you might agree with me. If not, I'll add it locally.

Evidence: https://cuisine.narkive.fr/cEqRE4GE/puis-je-utiliser-de-l-okara-frais-sans-le-cuire#
Original: https://cooking.stackexchange.com/questions/13714/can-i-use-fresh-okara-without-cooking-it

**Comment by quenhus** [comment]
Thanks a lot!

I'm going to block theses domains, as I consider automatic translation annoying.

- narkive.fr
- narkive.com
- narkive.co.il
- narkive.it
- narkive.no
- narkive.se
- narkive.dk
- narkive.fi
- narkive.kr
- narkive.ee
- narkive.pl
- narkive.info.tr
- narkive.hr
- narkive.cz
- narkive.in

Do not hesitate to submit other website of the narkive group.

Thanks again.
