### ISSUE TITLE
Request: splunktool.com

### ISSUE THREAD

**Issue by GlassGruber** [quenhus/uBlock-Origin-dev-filter#321]
Evidence: https://splunktool.com/how-to-test-if-object-is-a-pathlib-path
Original: https://stackoverflow.com/questions/58647584/how-to-test-if-object-is-a-pathlib-path

Isn't this also some copyright fringe stuff for splunk?

Btw thanks for this list!

**Comment by quenhus** [comment]
Thanks a lot for your contribution!
