### ISSUE TITLE
Request: add erg.tcta.com.au to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#325]
Evidence: http://erg.tcta.com.au/questions/4651437/how-do-i-set-a-variable-to-the-output-of-a-command-in-bash
Original: https://stackoverflow.com/questions/4651437/how-do-i-set-a-variable-to-the-output-of-a-command-in-bash

**Comment by quenhus** [comment]
Thanks a lot!
Also:
Evidence: https://quick-advisors.com/why-do-i-need-to-store-my-bash-output-in-variables/
Evidence: https://mulloverthing.com/how-to-set-commands-output-as-a-variable-in-a-batch-file/
Evidence: https://www.linuxfixes.com/2022/09/solved-how-do-i-set-variable-to-output.html?m=1
