### ISSUE TITLE
Request: add bountysource.com to the filter

### ISSUE THREAD

**Issue by yokoffing** [quenhus/uBlock-Origin-dev-filter#330]
Evidence: https://app.bountysource.com/teams/ghacksuserjs/issues?tracker_ids=55128897
Original: https://app.bountysource.com

**Comment by Nothing4You** [comment]
you do realize that both are the same domain?

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

I'm not sure this website is a useless copycat of GitHub. It seems it allows to have bounties for resolving issues on open-source projects. It sounds interesting, but I don't know how "real" it is.

**Comment by Nothing4You** [comment]
afaik bountysource is a legitimate service, at least they've been there for a good number of years and i've seen a few projects using them before.

**Comment by quenhus** [comment]
Thanks for the information @Nothing4You. I'm closing the issue: bountysource seems legitimate to me.
