### ISSUE TITLE
c-sharpcorner.com blocked mistakenly?

### ISSUE THREAD

**Issue by Merlin04** [quenhus/uBlock-Origin-dev-filter#339]
It seems like c-sharpcorner.com has been blocked, although it appears to be a legitimate website (I remember using it quite a bit back in my C# days).

**Comment by xvello** [comment]
This site has been added to the "SEO spam" list in https://github.com/quenhus/uBlock-Origin-dev-filter/pull/227.

@quenhus might shed some light on what the intended scope for this new list is. In the meantime, you can use the smaller `dev` filter set, that does not include the "SEO spam" list.
