### ISSUE TITLE
Request: add stackprinter.com to the filter

### ISSUE THREAD

**Issue by AgentRev** [quenhus/uBlock-Origin-dev-filter#344]
Evidence: http://www.stackprinter.com/export?service=stackoverflow&question=218123&printer=false
Original: https://stackoverflow.com/questions/218123/what-was-the-strangest-coding-standard-rule-that-you-were-forced-to-follow

**Comment by quenhus** [comment]
Thanks a lot!

**Comment by stdedos** [comment]
Have you ever saw actual search engine results that reference stackprinter.com? 😕

It is a helpful little site to make the results printable. I don't think it warrants to be blocked
At least, please remove the `||stackprinter.com^$all` rule - it affects loading of site resources

**Comment by AgentRev** [comment]
I knew stackprinter wasn't malicious when I reported it, but it did show up multiple times in my search results. I'm not exactly sure why the site owner didn't simply disable search engine indexing of its `/export` page. I agree tho, the `||` part should probably be not be present in the final filter, if the filter generator supports such an option.
