### ISSUE TITLE
Request: add breadybready.blogspot.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#347]
Evidence: http://breadybready.blogspot.com/2013/07/ruby-rvm-cannot-install-thrift-on.html
Original: https://stackoverflow.com/questions/15839455/rvm-cannot-install-thrift-on-amazon-linux-checking-strlcpy-in-string-h

**Comment by quenhus** [comment]
Thanks a lot!

Closed by 373073ad43178db1582ddab03c55c76be56bf76b
