### ISSUE TITLE
Request: add tagmerge.com to the filter

### ISSUE THREAD

**Issue by AndrewKvalheim** [quenhus/uBlock-Origin-dev-filter#356]
Evidence: https://tagmerge.com/question/rebase-failed-cannot-merge-binary-files-monopolee-xlsx

Original: https://stackoverflow.com/questions/71813809/rebase-failed-cannot-merge-binary-files-monopolee-xlsx/71855238#71855238

**Comment by quenhus** [comment]
Thanks a lot!
