### ISSUE TITLE
DuckDuckGo and Brave .onion address

### ISSUE THREAD

**Issue by m3thm4th** [quenhus/uBlock-Origin-dev-filter#368]
The .onion addresses of DuckDuckGo and Brave should be added in the list

https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion

https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion

**Comment by quenhus** [comment]
Thanks for your contribution. To be honest, I don't have time to add support for .onion addresses. 

However, I would be pleased to accept a pull request.
