### ISSUE TITLE
DuckDuckGo: npm.io filter filters out pnpm.io

### ISSUE THREAD

**Issue by Vildis** [quenhus/uBlock-Origin-dev-filter#369]
pnpm.io isn't a npm package repository copycat but an alternative npm package manger

**Comment by quenhus** [comment]
Hi,
Thanks for your contribution.
You are right, there is an issue with pnpm.io because of the contain filter `a[href*="npm.io"]`

I don't have an appropriate solution to that. Maybe have two filters.

I think I'm going to remove npm.io from the filter list until we find a solution.
