### ISSUE TITLE
Suggestion: Add adblockers install list to the README.md

### ISSUE THREAD

**Issue by S-trace** [quenhus/uBlock-Origin-dev-filter#37]
Maybe it will be useful to add the ad blockers install list to the README.md document (in case a user has no ad blocker installed yet)?

A nice list is in a https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/README.md file (in the `AdBlock Filter` section)

Sorry for the block-request label (this is not a block request) but I haven't clicked the "submit blank issue" for this issue when creating(

**Comment by S-trace** [comment]
Sorry for block-request label (this is not a block request) but I don't know how to submit an issue without this label.

**Comment by quenhus** [comment]
Thanks for your contribution!

I'm not sure with which add-ons the filter works. For now, I'm only sure the filter work with uBlock Origin.

For your information you can open blank issue here :
<img src="https://i.imgur.com/RvQqXwu.png" width="600px">

You can also remove the label of the issue at the right of the UI.

**Comment by quenhus** [comment]
After verification, the filter doesn't work with Adblock Plus and I'm not sure it works with other adblock add-ons.
