### ISSUE TITLE
Request: add multiple fake urls to the filter

### ISSUE THREAD

**Issue by rk-exxec** [quenhus/uBlock-Origin-dev-filter#372]
These pages are all identical in content but disguise themselves as pyqt help pages.

https://blx.vdw-zulassung.de/pyqt-qthread-blocking-gui.html
https://spx.ev-select.de/en/pyqt-qthread-blocking-gui.html
https://fjrrlx.tierservice-ohv.de/pyqt-qthread-blocking-gui.html
https://vpxs.sushi-mizumi.de/pyqt-qthread-blocking-gui.html
https://rnn.innereprozesse.de/pages/pyqt-qthread-blocking-gui.html
https://ljso.niuberlin.de/pyqt-qthread-blocking-gui.html

https://favi.netzzwerk.de/pyside2-threading-example.html
https://toen.musik-im-isebekpark.de/pyside2-threading-example.html

I'm not sure this fits the mission of the filter, but it is spam on the first page when googling for python qt help.
Seem to be stolen domains too.

**Comment by quenhus** [comment]
Thanks! Sorry for my late response. Mirrors seem to be down now (even though they are redirecting to malicious websites.)

Could you confirm that the domains you listed are not mirroring pyqt pages anymore?

I'm adding a tag on this issue, to be able to find these domains if they are back online.
