### ISSUE TITLE
Request: add plageroyale.com to the filter

### ISSUE THREAD

**Issue by Nothing4You** [quenhus/uBlock-Origin-dev-filter#373]
Not sure if you want to include reddit?

Evidence: https://www.plageroyale.com/p/netsec/comments/11g2lzp/taking_over_bookingcom_accounts_by_abusing_oauth/
Original: https://www.reddit.com/r/netsec/comments/11g2lzp/taking_over_bookingcom_accounts_by_abusing_oauth/

**Comment by quenhus** [comment]
Thanks a lot! I will add it as SEO spam for now.
