### ISSUE TITLE
Unblock narkive.com

### ISSUE THREAD

**Issue by m3thm4th** [quenhus/uBlock-Origin-dev-filter#375]
It's a newsgroup, and anyway has nothing to do with search engines

**Comment by quenhus** [comment]
The issue #317 highlight that narkive is doing automatic translation of Stackoverflow contents. It is a deceptive behavior to me, as explain in [this filter scope](https://github.com/quenhus/uBlock-Origin-dev-filter#scope-of-this-filter).

However, I can't  deny that Narkive websites have original and interesting content, but it is mixed up with deceptive copycats.
