### ISSUE TITLE
Request: add https://thesassway.com/ to the SEO website filter

### ISSUE THREAD

**Issue by appeasementPolitik** [quenhus/uBlock-Origin-dev-filter#376]
SEO spam website. At first sight look normal but is robot generated, like at this link:

https://thesassway.com/what-is-a-critical-region-in-computer-science/

The images don't make any sense (why is there a brain?) and the information is very questionable. It looks like headers are searched blindly to find images for the website. If you go to the editors page, it reveals over 1600 pages of blog posts written. I also found a case where there were 25 blog posts made in one day on April 8th:

https://thesassway.com/author/lorraine/page/4/

An example where the image search goes wrong, causing the CSGO map Cache to be shown instead of an image about CSS cache:

https://thesassway.com/how-to-force-a-cache-update-for-your-css/

Also contact only contains info about advertising:

https://thesassway.com/contact-us/

**Comment by quenhus** [comment]
Thanks a lot!
