### ISSUE TITLE
Request: add SEO spam URLs to the filter

### ISSUE THREAD

**Issue by Avamander** [quenhus/uBlock-Origin-dev-filter#377]
Please add these SEO spam domains to the filter 

```
theyardqatar.com
shopwaxpoetic.com
azazworld.com
d-chest.cfd
fornerianicolo.it
aqsana.de
rtscleaningservices.com
```

**Comment by katastrophe92** [comment]
Hey! Sorry for being a noob. What is SEO? Thanks!

**Comment by appeasementPolitik** [comment]
Search Engine Optimization

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

It is hard to determine whether a domain is doing SEO spam. I'm trying to maintain a block list as tiny as possible, to preserve its relevance.

It could help if anyone could provide evidence of "annoyance" for each domain.

Thanks again!

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

It is hard to determine whether a domain is doing SEO spam. I'm trying to maintain a block list as tiny as possible, to preserve its relevance.

It could help if anyone could provide evidence of "annoyance" for each domain.

Thanks again!
