### ISSUE TITLE
Request: More SEO spam websites

### ISSUE THREAD

**Issue by appeasementPolitik** [quenhus/uBlock-Origin-dev-filter#378]
```
https://digitalmagazine.org/
https://www.fortech.org/
https://techbar.org/
```
Seem very related to each other, have a very similar footer and 'Submit a guest post' / 'Contact us' page

**Comment by appeasementPolitik** [comment]
Here's one more: 

`https://wp.flash-jet.com/`

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

It is hard to determine whether a domain is doing SEO spam. I'm trying to maintain a block list as tiny as possible, to preserve its relevance.

It could help if anyone could provide evidence of "annoyance" for each domain.

Thanks again!
