### ISSUE TITLE
Request: add fake shops to the filter

### ISSUE THREAD

**Issue by dyarochewsky** [quenhus/uBlock-Origin-dev-filter#382]
https://555sq.com.cn
https://prorify.de
https://milgenial.uy
https://swuso.com
https://cebubestbuy.com
https://love-pdf.com
https://buyyeezy2023.com
https://casavec.com
https://kingcampoutdoors.co.jp
https://imlb2c.com
https://wareeb.pk
https://loepwatch.com
https://fiewatch.com
https://felara.com.do
https://posehee.com
https://shapelocator.com
https://beautyt.shop
https://lomoor.com
https://morlyes.com
https://ajcenteruss.com
https://bitiiy.com
https://storagestory.com
https://ihuers.com
https://bloomessentialsbrand.com
https://quitasueno.com
https://lifestyletrading.co.za
https://yyderfreap.shop
https://audiosg.com.sg
https://fujibikes.com
https://walmartchina.top
https://geldencosmeticos.com
https://sellfox.com
https://parklaneupholstemk.com
https://iteeus.com
https://monark-store.com
https://shapeden.com
https://andamente.pt
https://staging.zendrop.com
https://courier-tracking.com
https://yofi-yofi.com
https://stellara.de
https://innomediacreate.com
https://sehaleservices.com
https://magnite.shop
https://decompraschile.com
https://salimusic.com
https://open-cbd.de
https://gourmetkitchenhouse.shop
https://onrunningshop.com
https://bygigi.mx
https://vkeys.online
https://teevpower.com
https://caraci.it
https://easyshopper.org
https://oncloudrun.shop
https://shopperexpress.shop
https://aoocib.com
https://7s4c.top
https://chandeco.com
https://networksfishing.com
https://millabay.com
https://mila-vica.de
https://ballsbags.com
https://vinisay.com
https://tinkleo.com
https://draxu.com
https://headsets4business.co.uk
https://kielorelief.io
https://olaoffer.shop
https://nosdaarte.com
https://pairmate.se
https://babybeddingdesign.com
https://coco-vip-shop.com
https://xunlei.it
https://botsuanah.com
https://lojaacasa.com.br
https://netsugar.shop
https://dashracegear.net
https://youthfy.shop
https://smartokids.com
https://pipopi.com
https://k-tozluxury.shop
https://zuozuoshoe.shop
https://vip-yuki-shop.com
https://c-tozluxury.shop
https://lasercutjewelry.net
https://sleepyfull.com
https://expofstore.com
https://watchmark.shop
https://carsaratek.com
https://xajzfwgs.com
https://uange.shop
https://imagemotorcycles.co.nz
https://twinsbio.com
https://snapchaty.com
https://tomfordgo.com
https://worthas.shop
https://microgull.com

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

While these sites are terrible, I can't consider them as copycats.

Also, I don't think I want to deal with shops in this filter. Maintaining a filter for devs already takes a lot of time (to verify one by one every mirror).

You might suggest these websites to :

-   uBlock filters – Annoyances (https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt)
-   Fanboy’s Annoyance (https://easylist.to/)
-   AdGuard Annoyance (https://github.com/AdguardTeam/AdguardFilters#adguard-filters)
