### ISSUE TITLE
Request: add gangofcoders.net to the filter

### ISSUE THREAD

**Issue by nashafa** [quenhus/uBlock-Origin-dev-filter#383]
Evidence: https://www.gangofcoders.net/solution/ios-use-of-hkobserverquerys-background-update-completionhandler/
Original: https://stackoverflow.com/questions/30143280/ios-use-of-hkobserverquerys-background-update-completionhandler

The copycat site also [explicitly states](https://www.gangofcoders.net/about-us/#:~:text=A%20fair%20amount%20of%20the%20content%20on%20our%20website%20is%20sourced%20from%20Stackoverflow.) that they source their content from Stackoverflow.

**Comment by quenhus** [comment]
Thanks a lot!
