### ISSUE TITLE
Request: add stackguides.com to the filter

### ISSUE THREAD

**Issue by kegelink** [quenhus/uBlock-Origin-dev-filter#384]
Evidence: https://stackguides.com/questions/55206348/how-do-i-force-a-complete-cold-start-of-an-aws-lambda-function-on-a-vpc
Original: https://stackoverflow.com/questions/55206348/how-do-i-force-a-complete-cold-start-of-an-aws-lambda-function-on-a-vpc

**Comment by quenhus** [comment]
Thanks a lot!
