### ISSUE TITLE
Request: add GitHub issue copycats to the filter

### ISSUE THREAD

**Issue by AndrewKvalheim** [quenhus/uBlock-Origin-dev-filter#395]
Evidence:

  - https://giterhub.com/repository/issues/quenhus/uBlock-Origin-dev-filter/395
  - https://githubissues.com/quenhus/uBlock-Origin-dev-filter/395

Original: https://github.com/quenhus/uBlock-Origin-dev-filter/issues/395

**Comment by quenhus** [comment]
Thanks a lot!
