### ISSUE TITLE
Request: uBlacklist compatible list export

### ISSUE THREAD

**Issue by NotaInutilis** [quenhus/uBlock-Origin-dev-filter#396]
Hi! Would it be possible for you to also publish your blocklist in a uBlacklist compatible format and add it to the readme so that everyone can subscribe easily? Your sources are already in a match pattern format, and some of them already come from uBlacklist blocklists, so it's a shame that it's not available in one click with the other lists. Unfortunately, I'm python illiterate so I can't do it myself.

As letsblock.it's search engine page states, it's more efficient than uB0 regarding search engine filtering and covers more services (Bing, Brave, DuckDuckGo, Ecosia, Qwant, Searx, Startpage.com, Yahoo! JAPAN and Yandex).

> Due to technical limitations, this template has lower performance and compatibility than dedicated extensions such as uBlacklist. We suggest testing this extension if you need compatibility with search engines we don't support, such as Bing.

**Comment by quenhus** [comment]
Hi!

I'm not sure to understand. The source data which generate all filters are already in uBlacklist format. 

For example, for [StackOverflow mirror list](https://github.com/quenhus/uBlock-Origin-dev-filter/blob/main/data/stackoverflow_copycats.txt), here is the static link you can use on uBlacklist : [https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/stackoverflow_copycats.txt](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/stackoverflow_copycats.txt).

I would also recommend using the uBlacklist option to block all subdomain by default.

**Comment by NotaInutilis** [comment]
Hi!

Seems like I didn't need to make an argument for uBlacklist after all! Sorry for the confusion it caused.

It's mostly a convenience request. Right now, adding all the source data you've aggregated here to uBlacklist requires to navigate to the data folder of this repository, find out your sources are in the right format, then add them one by one in uBlacklist.

You've done a great job to get these lists all together for easy distribution and kept them updated with more data than in their original repositories, so it'd be nice to add another couple buttons to your [Import into uBlock Origin](https://github.com/quenhus/uBlock-Origin-dev-filter#import-into-ublock-origin) table with these compiled lists in the uBlacklist format, ready to be subscribed in one (or two) clicks.

**Comment by quenhus** [comment]
Hi!

I just updated the README and the script that generate output to provide a better uBlacklist filter. I also provide a `/etc/hosts` and domains list format.

You can find more information [in the README](https://github.com/quenhus/uBlock-Origin-dev-filter#other-filter-formats-ublacklist-hosts-filter-)

**Comment by NotaInutilis** [comment]
Nice! Thanks!
