### ISSUE TITLE
Request: add qexe.de to the filter

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [quenhus/uBlock-Origin-dev-filter#401]
Evidence: https://qexe.de/question/wie-kann-ich-das-alte-win7-8-uac-dialogfeld-wieder-in-windows-10-anniversary-update-abrufen
Original: https://superuser.com/questions/1119982/how-can-i-get-the-old-win7-8-uac-dialog-back-in-windows-10-anniversary-update

Machine translated to German.

**Comment by quenhus** [comment]
Thanks a lot for your contribution!
