### ISSUE TITLE
Request: add minecraft.fandom.com (and others) to the filter

### ISSUE THREAD

**Issue by jendrikw** [quenhus/uBlock-Origin-dev-filter#405]
Evidence: https://minecraft.fandom.com/wiki/Cow
Original: https://minecraft.wiki/w/Cow

The Minecraft Wiki admins have migrated from fandom to a different platform (now at minecraft.wiki). The old fandom wiki is no longer maintained, but can't be deleted. For that reason, I now consider it SEO-Spam, as all users usually want the most up to date and "official" version. The fandom wiki is also full of ads.

Hostnames to be blocked are
minecraftwiki.net
minecraft.gamepedia.com
minecraft.fandom.com

Sources:
https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom
https://minecraft.fandom.com/wiki/Minecraft_Wiki:Moving_from_Fandom

**Comment by quenhus** [comment]
Hi,
Thanks for your contribution.

I understand the issue, but I have no way to redirect users to the correct wiki. I can only hide results and block domains. 

I think it might be deceptive for users, to have these domains blocked, while they were the official wikis for a decade.

What is your opinion one that?

**Comment by jendrikw** [comment]
As they are no longer the official wikis and may contain outdated information, users should be aware of it and prefer other sites. I don't think it's deceptive as people who use this filter are very aware that they won't see some search results.

**Comment by NotaInutilis** [comment]
For the specific SEO problem that is fandom, hiding results does not help with visibility of the new official wikis. The maintainer of the Indie Wiki Buddy extension is working on search results redirection, you might want to check it out. https://github.com/KevinPayravi/indie-wiki-buddy

For other wikis that are not independent, there's also the wikigg redirector which actually overwrites search results on a couple of search engines. https://github.com/alex4401/wikigg-redirect-extension

**Comment by jendrikw** [comment]
When people click on minecraft.wiki instead of fandom (because they can't see it), it should increase the ranking of minecraft.wiki.
