### ISSUE TITLE
Request: add git.histb.com to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#409]
Evidence: https://git.histb.com/quenhus/uBlock-Origin-dev-filter
Original: https://github.com/quenhus/uBlock-Origin-dev-filter

Evidence: https://git.histb.com/topics/hostsfile
Original: https://github.com/topics/hostsfile

**Comment by quenhus** [comment]
Hi !

Thanks a lot for your contribution.

The domain seems to be down right now. To keep the block list as small as possible, I'm going to wait for it to be up to add it.

**Comment by quenhus** [comment]
Thanks a lot!
