### ISSUE TITLE
Request: add bleepingcoder.com to the filter

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [quenhus/uBlock-Origin-dev-filter#410]
Evidence: https://bleepingcoder.com/nodemon/287577614/how-to-make-nodemon-auto-restart-a-program-on-crash-without
Original: https://github.com/remy/nodemon/issues/1221

**Comment by quenhus** [comment]
Thanks a lot!
