### ISSUE TITLE
Request: add devdoc.net to the filter

### ISSUE THREAD

**Issue by jendrikw** [quenhus/uBlock-Origin-dev-filter#411]
Evidence: http://devdoc.net/web/developer.mozilla.org/en-US/docs/Web/API/Notification/requireInteraction.html
Original: https://developer.mozilla.org/en-US/docs/Web/API/Notification/requireInteraction

SEO spam, and very out of date, with some articles from 2016 and 2017.

**Comment by quenhus** [comment]
Thanks a lot!
