### ISSUE TITLE
Request: add stackovercoder.com.de to the filter

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [quenhus/uBlock-Origin-dev-filter#412]
Evidence: https://stackovercoder.com.de/programming/23492043/change-default-timeout-for-mocha
Original: https://stackoverflow.com/questions/23492043/change-default-timeout-for-mocha

Horribly machine-translated to German.

**Comment by quenhus** [comment]
Thanks a lot!
