### ISSUE TITLE
Request: add github-wiki-see.page to the filter

### ISSUE THREAD

**Issue by simao** [quenhus/uBlock-Origin-dev-filter#419]
Evidence: https://github-wiki-see.page/m/swaywm/sway/wiki/GTK-3-settings-on-Wayland
Original: https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

**Comment by quenhus** [comment]
Thanks a lot! 

As explained in data/github_copycats.txt, Github wikis are not indexed by search engine, because of Github.

> github-wiki-see.page is a service that allows indexing of GitHub Wikis that GitHub blocks indexing of which is nearly all of them.
> At the moment, only about a couple thousand GitHub Wikis are permitted to be indexed out of about 420,000 in existence.
> Please visit https://github-wiki-see.page for a more thorough and/or updated explanation of the situation.
> It's actually a helpful GitHub copycat.
> If you're annoyed at the service's interstitial, you may want to look at the service's Auto Redirect API document
> for examples/details/implementation to automatically redirect to GitHub.com's Wiki if you land on the service:
> https://github.com/nelsonjchen/github-wiki-see-rs/blob/master/AUTO_REDIRECT_API.md

I won't block it until Github allows all wikis to be indexed.

**Comment by nelsonjchen** [comment]
I want to add that https://github-wiki-see.page/ automatically auto-redirects wikis that are detected to be indexable under the currently observed criteria. If/when GitHub allows that to happen, no one else needs to lift a finger and the site is "invisible".
