### ISSUE TITLE
Request: add sites to the filter

### ISSUE THREAD

**Issue by emielderckx** [quenhus/uBlock-Origin-dev-filter#42]
Please block https://news24lite.com
Evidence: https://news24lite.com/github.com
Original: github.com

Please block https://githubmemory.com/
Original: github.com

Please block https://github.phala.one/
Original: github.com

Please block https://google-yandex.info
Original: github.com
Evidence: 
![image](https://user-images.githubusercontent.com/35953244/154852362-6a96ed63-6c99-4ee4-b074-3a823e3a8b3f.png)

**Comment by quenhus** [comment]
Thanks!

For your information, `githubmemory.com` was already blocked by this filter. Do you have any issue with the block of this domain? (Might occur if it uses a subdomain for example)
