### ISSUE TITLE
Request: add dogovori.info to the filter

### ISSUE THREAD

**Issue by AndrewKvalheim** [quenhus/uBlock-Origin-dev-filter#45]
Evidence: https://dogovori.info/questions/45671200/safari-not-requesting-srcset-images-on-resize
Original: https://stackoverflow.com/questions/45671200/safari-not-requesting-srcset-images-on-resize

![Screenshot 2022-02-20 at 21-00-44 ios safari srcset zoom - Google Search](https://user-images.githubusercontent.com/1844746/154892369-478ef3a7-cc95-47fc-8abd-4d96a5157e44.png)

Thanks!

**Comment by quenhus** [comment]
Thanks!
