### ISSUE TITLE
Request: add sites to the filter

### ISSUE THREAD

**Issue by emielderckx** [quenhus/uBlock-Origin-dev-filter#46]
Evidence: https://hub.fastgit.org or https://endpoint.fastgit.org
Original: https://github.com
![image](https://user-images.githubusercontent.com/35953244/154934614-c5db0500-80cf-4177-9b28-63f088d55f1c.png)

Evidence: https://javarepos.com
Original: https://github.com
![image](https://user-images.githubusercontent.com/35953244/154934967-d0bb8e78-3a4e-4dfc-8c0d-0568d947b413.png)

Evidence: https://githubmemory.com/repo/plasmoapp/plasmo-voice/issues/74
Original: https://github.com/plasmoapp/plasmo-voice/issues/74
![image](https://user-images.githubusercontent.com/35953244/154935161-8e503a4b-44bf-4ccb-89f4-af87bbf5b9b6.png)

Evidence: https://coder.social
Original: https://github.com
![image](https://user-images.githubusercontent.com/35953244/154935763-8af3e20d-182f-427e-8e5b-17a748c38071.png)

**Comment by quenhus** [comment]
Thanks!
