### ISSUE TITLE
Request: add wikipedia sites to the filter

### ISSUE THREAD

**Issue by emielderckx** [quenhus/uBlock-Origin-dev-filter#47]
Evidence: https://de.zxc.wiki
Original: wikipedia

Evidence: https://en.wikivoyage.org
Original: wikipedia

Evidence: https://nl.frwiki.wiki (uses also subdomains: de.frwiki.wiki etc.)
Original: wikipedia

**Comment by quenhus** [comment]
Thanks!

Wikivoyage is part of the Wikimedia Foundation family, and is not a copycat. It is a world-wide travel guide managed by the Wikimedia Foundation.
