### ISSUE TITLE
Request: add these sites to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#49]
I never thought much about these copycat sites, until this...
https://www.google.com/search?q=baldur+site:fuscin.com

Practically fell backward outta my chair!

{funny enough, this comes up blank, lol: https://www.google.com/search?q=quenhus+site%3Afuscin.com}

Github copycats. (haven't checked if they copy other sites)

Evidence: https://www.fuscin.com/btigi/iiTweak  
Original: https://github.com/btigi/iiTweak

Evidence: https://iboxshare.com/quenhus/uBlock-Origin-dev-filter
Original: https://github.com/quenhus/uBlock-Origin-dev-filter

**Comment by quenhus** [comment]
Thanks!
