### ISSUE TITLE
Request: add grokbase.com to the filter

### ISSUE THREAD

**Issue by S-trace** [quenhus/uBlock-Origin-dev-filter#52]
Evidence: https://grokbase.com/t/gg/android-ndk/164k67v5fq/how-to-dynamically-get-the-current-compiler-target-file-name-in-android-mks-local-cflags
Original: https://stackoverflow.com/questions/36721648/how-to-dynamically-get-the-current-compiler-target-file-name-in-android-mks-loc

**Comment by quenhus** [comment]
Thanks!
