### ISSUE TITLE
Request: add all this author's websites to the filter

### ISSUE THREAD

**Issue by nelsonjchen** [quenhus/uBlock-Origin-dev-filter#53]
Evidence: https://www.google.com/search?q=winterswgrose49%40gmail.com

Original: see their sites, all of them

**Comment by nelsonjchen** [comment]
We might want to also take advantage of the comment functionality in the source lists to categorize the sites.

**Comment by quenhus** [comment]
Thanks!

Do we agree all these sites are Github copycats?

**Comment by quenhus** [comment]
Here is the list of unique domains I found:

```
*://bestofvue.com/*
*://golangrepo.com/*
*://swiftobc.com/*
*://pythonrepo.com/*
*://flutterrepos.com/*
*://androidrepo.com/*
*://bestofflutter.com/*
*://jsrepos.com/*
*://macosrepo.com/*
*://javarepos.com/*
*://zzun.app/*
*://rustrepo.com/*
*://bestofreactjs.com/*
*://bestofphp.com/*
*://bestofcpp.com/*
*://bestofjava.com/*
```

**Comment by nelsonjchen** [comment]
I think some of them are already on the list as copycats. Some are new like macosrepo.com.

**Comment by quenhus** [comment]
Yep, no problem with that. The build tool automatically remove duplicate. 

I will add them tomorrow.

**Comment by nelsonjchen** [comment]
These all share a very similar template so maybe it might be worth revisiting some of the existing copycats as welland seeing if there's a way to bulk discover similar re-labeled variations too.

**Comment by quenhus** [comment]
Yes we should do that. I will see what I can do.
