### ISSUE TITLE
Request: add wp-qa.com to the filter

### ISSUE THREAD

**Issue by AndrewKvalheim** [quenhus/uBlock-Origin-dev-filter#54]
Evidence: https://wp-qa.com/wp_rest_response-to-download-a-file  
Original: https://stackoverflow.com/questions/44524071/wp-rest-response-to-download-a-file

![screenshot of https://www.google.com/search?q=WP_REST_Response+csv](https://user-images.githubusercontent.com/1844746/155431565-611d33b5-b4d8-4f30-825c-0728310b4c65.png)

**Comment by quenhus** [comment]
Thanks!
