### ISSUE TITLE
Request: add programmierfrage.com to the filter

### ISSUE THREAD

**Issue by rubenvanerk** [quenhus/uBlock-Origin-dev-filter#56]
Evidence: https://programmierfrage.com/items/making-text-disappear-using-laravel-livewire-by-timing-out-the-flash-message  
Original: https://stackoverflow.com/questions/70584734/making-text-disappear-using-laravel-livewire-by-timing-out-the-flash-message

**Comment by quenhus** [comment]
Thanks!
