### ISSUE TITLE
Request: add tutorialmeta.com to the filter

### ISSUE THREAD

**Issue by realAzazello** [quenhus/uBlock-Origin-dev-filter#61]
Evidence: https://tutorialmeta.com/question/bookmarklet-containing-a-button
Original: https://stackoverflow.com/questions/50040152/bookmarklet-containing-a-button

Doesn't seem like this site has fully copied SOF yet, as the domain is probably very new, this year.
Here's a funny, at the bottom of each page: "© 2022 All rights reserved"

**Comment by Oondanomala** [comment]
It seems as the website also has unique content, but all the questions are under `tutorialmeta.com/question`, so it should only block that

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

It seems that 99.9% of the content is from StackOverflow. It is quite a strange project, which uses SO content for growth hacking. Is there real interest not to block this website?

**Comment by quenhus** [comment]
Filtering `tutorialmeta.com/question/*` would not block these pages that contain only SO content: 
- tutorialmeta.com/wordpress
- tutorialmeta.com/database
- tutorialmeta.com/shopify
- tutorialmeta.com/laravel
- tutorialmeta.com/git
- ...

**Comment by Oondanomala** [comment]
Right, i didn't think of that.
I guess its probably not worth it then
