### ISSUE TITLE
Request: add softbranchdevelopers.com to the filter

### ISSUE THREAD

**Issue by stillhart-at-bechterew** [quenhus/uBlock-Origin-dev-filter#65]
### Reddit:
Evidence: https://softbranchdevelopers.com/typescript-type-substitution-for-proptypes-type/
Original: https://www.reddit.com/r/reactjs/comments/oyxbfn/typescript_type_substitution_for_proptypes_type/

### Github:
Evidence: https://softbranchdevelopers.com/a-simple-vue-js-app-made-for-learning-the-framework-and-how-to-work-with-api/
Original: https://github.com/matteotagliatti/movie-vue-app?ref=vuejsexamples.com

Evidence: https://softbranchdevelopers.com/starter-pack-for-creating-ui-kit-on-vue-js/
Original: https://github.com/NorvikIT/vue-uikit-starter?ref=vuejsexamples.com

### Comments
Sometimes there are non-human generic comments like the one on this article:
https://softbranchdevelopers.com/learn-swift-for-c-developers/

### Thanks:

1. Thank for for the awesome filterlist. I didn't knew the situation is so bad until I started working with more javascript technology. I thought it's just a myth that the situation is getting out of control. 
2. Do you plan to also include reddit copycats?

**Comment by quenhus** [comment]
Thanks for your contribution with this terrible website (with ads).

I might add a list dedicated to Reddit in the future.
