### ISSUE TITLE
Request: add vuejscode.com to the filter

### ISSUE THREAD

**Issue by stillhart-at-bechterew** [quenhus/uBlock-Origin-dev-filter#67]
# stackoverflow
Evidence: https://vuejscode.com/vue-typescript-how-to-annotate-computed-with-types
Original: https://stackoverflow.com/questions/69905506/vue-typescript-how-to-annotate-computed-with-types

Evidence: https://vuejscode.com/javascript-async-function-throws-error-when-using-await
Original: https://stackoverflow.com/questions/70710701/javascript-async-function-throws-error-when-using-await

# github
Evidence: https://vuejscode.com/vue-play
Original: https://github.com/vue-play/vue-play

# Thank you a lot for your work and effort

**Comment by quenhus** [comment]
Thanks a lot!

Closes by #68
