### ISSUE TITLE
Request: add bikehike.org + others to the filter

### ISSUE THREAD

**Issue by purpleyuan** [quenhus/uBlock-Origin-dev-filter#73]
All sites: 
- https://bikehike.org/what-muscles-does-cycling-tone/
- https://allfamousbirthday.com/faqs/does-cycling-give-you-a-big-bum/
- https://iron-set.com/us/how-do-you-build-your-outer-thigh-muscle/
- https://wikipedikia.org/is-20-minutes-of-cycling-a-day-enough/

Original: https://www.welovecycling.com/wide/2018/06/21/embracing-strong-legs-how-cycling-does-doesnt-change-a-womans-body/

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

You might suggest these websites to :
 - uBlock filters – Annoyances (https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt)
 - Fanboy’s Annoyance (https://easylist.to)
 - AdGuard Annoyance (https://github.com/AdguardTeam/AdguardFilters#adguard-filters)

**Comment by purpleyuan** [comment]
Ah, my bad. I missed this was mostly for Github/SO copycat sites. I was just looking for a way to ban sites like these from my own searches, but I can edit that in myself.

Thanks for your work!

**Comment by quenhus** [comment]
Also, you can use https://letsblock.it/filters/search-results to generate filters for website you want. (You can also use my tool in `/src/`, but it is not as easy)

**Comment by purpleyuan** [comment]
I actually did find that on your readme just now! I should have read it more closely the first time around, haha. I just got excited about this tool. I really appreciate it and am certainly putting it to good use.
