### ISSUE TITLE
Request: add libhunt.com to the filter

### ISSUE THREAD

**Issue by matteoturini** [quenhus/uBlock-Origin-dev-filter#74]
Evidence: https://www.libhunt.com/posts/369911-fidelityfx-cli-command-line-tool-that-processes-image-files-using-the-fidelityfx-super-resolution-fsr-shader-system
Original: https://github.com/GPUOpen-Effects/FidelityFX-CLI/

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

I'm not sure this website is a copycat. It doesn't directly copy contents from GitHub, but rather gathers multiple sources to establish a popularity score. Is `libhunt.com` really an annoyance? Did it rank higher in search engine than the original GitHub repo?

**Comment by matteoturini** [comment]
> Is libhunt.com really an annoyance?
> Did it rank higher in search engine than the original GitHub repo?

Yes. It ranks MUCH higher than github.
