### ISSUE TITLE
Request: add githublab.com to the filter

### ISSUE THREAD

**Issue by freeatnet** [quenhus/uBlock-Origin-dev-filter#76]
Evidence: https://githublab.com/repository/issues/edgedb/edgedb/3435
Original: https://github.com/edgedb/edgedb/issues/3435

**Comment by realAzazello** [comment]
Evidence: https://githublab.com/repository/issues/SmartPack/SmartPack-Kernel-Manager
Original: https://github.com/SmartPack/SmartPack-Kernel-Manager/issues?q=is%3Aissue+

Evidence: https://githublab.com/repository/SmartPack/SmartPack-Kernel-Manager
Original: https://github.com/SmartPack/SmartPack-Kernel-Manager
