### ISSUE TITLE
Request: add catwolf.org to the filter

### ISSUE THREAD

**Issue by devvick** [quenhus/uBlock-Origin-dev-filter#87]
Evidence: https://catwolf.org/qs?id=d234aa5c-96e5-4051-8272-55d12dcd2859&x=y
Original: https://stackoverflow.com/questions/58145662/error-conditions-must-be-prefaced-by-a-vendor-on-creating-role-in-aws-cdk

**Comment by quenhus** [comment]
Thanks a lot!
