### ISSUE TITLE
Search result removal not working for DDG

### ISSUE THREAD

**Issue by zjtalia** [quenhus/uBlock-Origin-dev-filter#89]
I have the DDG and Google bundle for Firefox. Links on the list are blocked in that I cannot access the sites, but results with those links are still showing up in search. Using this rule instead of the current one does remove the result however:

`duckduckgo.*##.results>div:has(a[href*="copycatsite.com"])`

**Comment by quenhus** [comment]
Thanks a lot!
Indeed, DDG seems to be changing its result page structure. I am going to update the filter.
